name: CI

# on:
#   push:
#     branches-ignore:
#       - main

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  backend_ci:
    name: CI backend
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v4
      - 
        name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - 
        name: Install dependencies
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          FRONTEND_URL: ${{secrets.FRONTEND_URL}}
          MAILER_FROM_ADDRESS: ${{secrets.MAILER_FROM_ADDRESS}}
        working-directory: backend
        run: composer install --prefer-dist --no-progress --no-interaction
      - 
        name: Run PHP CS Fixer
        working-directory: backend
        run: |
          vendor/bin/php-cs-fixer fix src --dry-run --diff
          vendor/bin/php-cs-fixer fix tests --dry-run --diff
      - 
        name: Run PHPStan
        working-directory: backend
        run: vendor/bin/phpstan analyse src
      - 
        name: Run PHPUnit tests
        working-directory: backend
        run: |
          php bin/phpunit --testsuite unit

  frontend_ci: 
    name: CI frontend
    runs-on: ubuntu-latest  
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v4
      - 
        name: Use Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 20.x
      - 
        name: Install dependencies
        working-directory: frontend
        run: npm ci 
      -
        name: Run ESLint
        working-directory: frontend
        run: npm run lint

  backend_tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    env:
      # DATABASE environment variables
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      PGADMIN_MAIL: ${{ secrets.PGADMIN_MAIL }}
      PGADMIN_PASSWORD: ${{ secrets.PGADMIN_PASSWORD }}
      # BACKEND environment variables
      CADDY_MERCURE_JWT_SECRET: ${{ secrets.CADDY_MERCURE_JWT_SECRET }}
      CORS_ALLOW_ORIGIN: ${{ secrets.CORS_ALLOW_ORIGIN }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
      JWT_PASSPHRASE: ${{ secrets.JWT_PASSPHRASE }}
      MAILER_DSN: ${{ secrets.MAILER_DSN }}
      MAILER_FROM_ADDRESS: ${{ secrets.MAILER_FROM_ADDRESS }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL_DEV }}
      # FRONTEND environment variables
      VITE_MAPBOX_TOKEN: ${{ secrets.VITE_MAPBOX_TOKEN }}
      VITE_API_URL: ${{ secrets.VITE_API_URL_DEV }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build Docker images
        uses: docker/bake-action@v6
        with:
          pull: true
          load: true
          files: |
            compose.yaml
            compose.override.yaml
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max
      -
        name: Start services
        run: docker compose up --wait --no-build
      -
        name: Check HTTP reachability
        run: curl -v --fail-with-body http://localhost
      -
        name: Check HTTPS reachability
        if: false # Remove this line when the homepage will be configured, or change the path to check
        run: curl -vk --fail-with-body https://localhost
      -
        name: Check Mercure reachability
        run: curl -vkI --fail-with-body https://localhost/.well-known/mercure?topic=test
      -
        name: Create test database
        if: false # Remove this line if Doctrine ORM is installed
        run: docker compose exec -T php bin/console -e test doctrine:database:create
      -
        name: Run migrations
        if: false # Remove this line if Doctrine Migrations is installed
        run: docker compose exec -T php bin/console -e test doctrine:migrations:migrate --no-interaction
      -
        name: Run PHPUnit
        if: false # Remove this line if PHPUnit is installed
        run: docker compose exec -T php bin/phpunit
      -
        name: Doctrine Schema Validator
        if: false # Remove this line if Doctrine ORM is installed
        run: docker compose exec -T php bin/console -e test doctrine:schema:validate
  lint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0