name: Development Pipeline

on:
  push:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  backend_ci:
    name: CI backend
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v4
      - 
        name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - 
        name: Install dependencies
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          FRONTEND_URL: ${{secrets.FRONTEND_URL}}
          MAILER_FROM_ADDRESS: ${{secrets.MAILER_FROM_ADDRESS}}
        working-directory: backend
        run: composer install --prefer-dist --no-progress --no-interaction
      - 
        name: Run PHP CS Fixer
        working-directory: backend
        run: |
          vendor/bin/php-cs-fixer fix src --dry-run --diff
          vendor/bin/php-cs-fixer fix tests --dry-run --diff
      - 
        name: Run PHPStan
        working-directory: backend
        run: vendor/bin/phpstan analyse src
      - 
        name: Run PHPUnit tests
        working-directory: backend
        run: |
          php bin/phpunit --testsuite unit

  frontend_ci: 
    name: CI frontend
    runs-on: ubuntu-latest  
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v4
      - 
        name: Use Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 20.x
      - 
        name: Install dependencies
        working-directory: frontend
        run: npm ci 
      -
        name: Run ESLint
        working-directory: frontend
        run: npm run lint